#! /bin/sh

# autostart
sxhkd &
xss-lock --transfer-sleep-lock -- i3lock --blur 5 clock &
picom -b
unclutter &
bash ~/.fehbg &
clipmenud &
bash ~/Scripts/polybar/bspwm-polybar.sh
dropbox &

# workspaces
# single monitor
bspc monitor -d ' MAIN ' ' CODE ' ' TOOL ' ' PLAY ' ' GAME ' ' VIRT ' ' FILE ' ' CONF ' ' CHAT ' ' WORK ' 
# dual monitor
#bspc monitor eDP-1 -d ' MAIN ' ' CODE ' ' TOOL ' ' PLAY ' ' GAME '
#bspc monitor DP-1 -d ' VIRT ' ' FILE ' ' CONF ' ' CHAT ' ' WORK '

bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# base16 tommorow night
bspc config normal_border_color   "#2E3440"
bspc config active_border_color   "#434C5E"
bspc config focused_border_color  "#D8DEE9"
bspc config presel_feedback_color "#3B4252"

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a jetbrains-idea desktop='^2'
bspc rule -a Steam desktop='^5'
bspc rule -a fantasygrounds.exe desktop='^5'
bspc rule -a telegram-desktop desktop='^9'
bspc rule -a slack desktop='^9'
bspc rule -a discord desktop='^9'
bspc rule -a 'Microsoft Teams - Preview' desktop='^9'
bspc rule -a spotify desktop='^4'
bspc rule -a 'VirtualBox manager' desktop='^6'

bspc rule -a 'Zathura' state='tiled'
